#pragma once

#include "SyntaxTree.hpp"
#include "Name.hpp"
#include "Statement.hpp"
#include "Statements.hpp"
#include "Function.hpp"
#include "Function_Main.hpp"
#include "Input.hpp"
#include "Print_Statement.hpp"
#include "If_Statement.hpp"
#include "While_Statement.hpp"
#include "Assign_Statement.hpp"
#include "Input_Statement.hpp"
#include "Initialization_Statement.hpp"
#include "Exit_Statement.hpp"

#include "Binary_Expression.hpp"
#include "Unary_Expression.hpp"
#include "Parenthesis_Expression.hpp"
#include "Semicolon_Expression.hpp"